-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 21:56:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_orari
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_orari` ;

-- -----------------------------------------------------
-- Schema DB_orari
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_orari` DEFAULT CHARACTER SET utf8 ;
USE `DB_orari` ;

-- -----------------------------------------------------
-- Table `DB_orari`.`Avviso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`Avviso` (
  `idAvviso` INT NOT NULL AUTO_INCREMENT,
  `descrizione` VARCHAR(1000) NOT NULL,
  `idCorso` VARCHAR(14) NULL,
  PRIMARY KEY (`idAvviso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`Lezione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`Lezione` (
  `idLezione` INT NOT NULL AUTO_INCREMENT,
  `idCorso` INT(11) NOT NULL,
  `argomento` DATETIME NULL,
  PRIMARY KEY (`idLezione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`Aula` (
  `idAula` INT(11) NOT NULL,
  `nomeAula` VARCHAR(45) NOT NULL,
  `edificio` VARCHAR(45) NOT NULL,
  `capienza` INT NOT NULL,
  PRIMARY KEY (`idAula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`CorsoDiLaurea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`CorsoDiLaurea` (
  `idCorsoDiLaurea` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrizione` VARCHAR(400) NOT NULL,
  `durata` INT(11) NOT NULL,
  `tipologia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCorsoDiLaurea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`Corso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`Corso` (
  `idCorso` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrizione` VARCHAR(45) NOT NULL,
  `idCorsoDiLaurea` INT(11) NULL,
  `annoDiCorso` INT(11) NOT NULL,
  INDEX `idCorsoDiLaurea_idx` (`idCorsoDiLaurea` ASC),
  PRIMARY KEY (`idCorso`),
  CONSTRAINT `idCorsoDiLaurea`
    FOREIGN KEY (`idCorsoDiLaurea`)
    REFERENCES `DB_orari`.`CorsoDiLaurea` (`idCorsoDiLaurea`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`Gruppo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`Gruppo` (
  `idGruppo` INT NOT NULL,
  `Descrizione` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGruppo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`Persona` (
  `idPersona` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `telefono` BIGINT(14) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `idGruppo` INT NOT NULL,
  INDEX `fk_ruolo_idx` (`idGruppo` ASC),
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `fk_gruppo`
    FOREIGN KEY (`idGruppo`)
    REFERENCES `DB_orari`.`Gruppo` (`idGruppo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`Esame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`Esame` (
  `idEsame` INT(11) NOT NULL,
  `nomeEsame` VARCHAR(45) NOT NULL,
  `dataOraInizio` DATETIME NOT NULL,
  `dataOraFine` DATETIME NOT NULL,
  `numeroIscritti` INT(5) NULL,
  `idCorso` VARCHAR(14) NOT NULL,
  `idProfessore` INT(11) NOT NULL,
  PRIMARY KEY (`idEsame`),
  INDEX `idProfessoreFk_idx` (`idProfessore` ASC),
  INDEX `idCorso_FK_corso_idx` (`idCorso` ASC),
  CONSTRAINT `idCorso_FK_corso`
    FOREIGN KEY (`idCorso`)
    REFERENCES `DB_orari`.`Corso` (`idCorso`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idProfessore_fk_Persona`
    FOREIGN KEY (`idProfessore`)
    REFERENCES `DB_orari`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`IscrizioneEsame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`IscrizioneEsame` (
  `idIscrizioneEsame` INT NOT NULL AUTO_INCREMENT,
  `idEsame` INT(11) NOT NULL,
  `giornoOra` DATETIME NOT NULL,
  `idStudente` INT(11) NOT NULL,
  `scadenzaLimiteIscrizione` DATETIME NOT NULL,
  `note` VARCHAR(45) NULL,
  PRIMARY KEY (`idIscrizioneEsame`),
  INDEX `idEsame_idx` (`idEsame` ASC),
  INDEX `idStudenteFk_idx` (`idStudente` ASC),
  CONSTRAINT `idStudenteFkPersona`
    FOREIGN KEY (`idStudente`)
    REFERENCES `DB_orari`.`Persona` (`idPersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idEsameFkEsame`
    FOREIGN KEY (`idEsame`)
    REFERENCES `DB_orari`.`Esame` (`idEsame`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`PrenotazioneAula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`PrenotazioneAula` (
  `idPrenotazioneAula` INT NOT NULL AUTO_INCREMENT,
  `giornoOraInizio` DATETIME NOT NULL,
  `giornoOraFine` DATETIME NOT NULL,
  `idAula` INT(11) NOT NULL,
  `idProfessore` INT(11) NOT NULL,
  PRIMARY KEY (`idPrenotazioneAula`),
  INDEX `idAula_idx` (`idAula` ASC),
  INDEX `idProfessoreFk3_idx` (`idProfessore` ASC),
  CONSTRAINT `idProfessore_FkPersona`
    FOREIGN KEY (`idProfessore`)
    REFERENCES `DB_orari`.`Persona` (`idPersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idAula_FkAula`
    FOREIGN KEY (`idAula`)
    REFERENCES `DB_orari`.`Aula` (`idAula`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`AulaLezione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`AulaLezione` (
  `idAulaLezione` INT(11) NOT NULL,
  `idAula` INT(11) NOT NULL,
  `idLezione` INT(11) NOT NULL,
  INDEX `fkIdLezione_idx` (`idLezione` ASC),
  PRIMARY KEY (`idAulaLezione`),
  CONSTRAINT `fkIdAula`
    FOREIGN KEY (`idAula`)
    REFERENCES `DB_orari`.`Aula` (`idAula`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdLezione`
    FOREIGN KEY (`idLezione`)
    REFERENCES `DB_orari`.`Lezione` (`idLezione`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`AulaEsame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`AulaEsame` (
  `idAulaEsame` INT NOT NULL AUTO_INCREMENT,
  `idAula` INT(11) NOT NULL,
  `idEsame` INT(11) NOT NULL,
  INDEX `fkIdAula_idx` (`idAula` ASC),
  INDEX `fkIdEsame_idx` (`idEsame` ASC),
  PRIMARY KEY (`idAulaEsame`),
  CONSTRAINT `idAulaFk4`
    FOREIGN KEY (`idAula`)
    REFERENCES `DB_orari`.`Aula` (`idAula`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idEsameFk4`
    FOREIGN KEY (`idEsame`)
    REFERENCES `DB_orari`.`Esame` (`idEsame`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`ProfessoreCorso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`ProfessoreCorso` (
  `idProfessoreCorso` INT(11) NOT NULL,
  `idProfessore` INT(11) NOT NULL,
  `idCorso` VARCHAR(14) NOT NULL,
  INDEX `idCorso_idx` (`idCorso` ASC),
  PRIMARY KEY (`idProfessoreCorso`),
  INDEX `idProfessoreFk5_idx` (`idProfessore` ASC),
  CONSTRAINT `idProfessoreFk5`
    FOREIGN KEY (`idProfessore`)
    REFERENCES `DB_orari`.`Persona` (`idPersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idCorsoFk5`
    FOREIGN KEY (`idCorso`)
    REFERENCES `DB_orari`.`Corso` (`idCorso`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`TipologiaRisorsa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`TipologiaRisorsa` (
  `idTipologiaRisorsa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descrizione` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipologiaRisorsa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`Risorsa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`Risorsa` (
  `idRisorsa` VARCHAR(40) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrizione` VARCHAR(45) NOT NULL,
  `idTipologiaRisorsa` INT NOT NULL,
  `commento` VARCHAR(300) NULL,
  PRIMARY KEY (`idRisorsa`),
  INDEX `fr_idTipologiaRisorsa_idx` (`idTipologiaRisorsa` ASC),
  CONSTRAINT `fr_idTipologiaRisorsa`
    FOREIGN KEY (`idTipologiaRisorsa`)
    REFERENCES `DB_orari`.`TipologiaRisorsa` (`idTipologiaRisorsa`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`PrenotazioneRisorsa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`PrenotazioneRisorsa` (
  `idPrenotazioneRisorsa` INT NOT NULL AUTO_INCREMENT,
  `giornoOraInizio` DATETIME NOT NULL,
  `giornoOraFine` DATETIME NOT NULL,
  `idRisorsa` VARCHAR(40) NOT NULL,
  `idProfessore` INT(11) NOT NULL,
  INDEX `idProiettore_idx` (`idRisorsa` ASC),
  INDEX `idProfessore0_idx` (`idProfessore` ASC),
  PRIMARY KEY (`idPrenotazioneRisorsa`),
  CONSTRAINT `idProfessore0`
    FOREIGN KEY (`idProfessore`)
    REFERENCES `DB_orari`.`Persona` (`idPersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idRisorsa`
    FOREIGN KEY (`idRisorsa`)
    REFERENCES `DB_orari`.`Risorsa` (`idRisorsa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`CalendarioDidattico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`CalendarioDidattico` (
  `idCalendarioAccademico` INT NOT NULL AUTO_INCREMENT,
  `nomeAnno` VARCHAR(45) NOT NULL,
  `inizioPeriodo` DATE NOT NULL,
  `finePeriodo` DATE NOT NULL,
  PRIMARY KEY (`idCalendarioAccademico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`OrarioDidattico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`OrarioDidattico` (
  `idOrarioDidattico` INT NOT NULL AUTO_INCREMENT,
  `giornoOraInizio` DATETIME NOT NULL,
  `giornoOraFine` DATETIME NOT NULL,
  `idLezione` INT(11) NOT NULL,
  PRIMARY KEY (`idOrarioDidattico`),
  INDEX `fkidLezione_idx` (`idLezione` ASC),
  CONSTRAINT `fkidLezione6`
    FOREIGN KEY (`idLezione`)
    REFERENCES `DB_orari`.`Lezione` (`idLezione`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`LezioneCorso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`LezioneCorso` (
  `idLezioneCorso` INT(11) NOT NULL AUTO_INCREMENT,
  `idCorso` VARCHAR(14) NOT NULL,
  `idLezione` INT(11) NOT NULL,
  INDEX `fk_idLezione_idx` (`idLezione` ASC),
  PRIMARY KEY (`idLezioneCorso`),
  CONSTRAINT `fk_idLezione`
    FOREIGN KEY (`idLezione`)
    REFERENCES `DB_orari`.`Lezione` (`idLezione`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `kf_idCorso`
    FOREIGN KEY (`idCorso`)
    REFERENCES `DB_orari`.`Corso` (`idCorso`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`Autenticazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`Autenticazione` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `idPersona` INT(11) NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_id_idx` (`idPersona` ASC),
  CONSTRAINT `fk_id`
    FOREIGN KEY (`idPersona`)
    REFERENCES `DB_orari`.`Persona` (`idPersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`GestioneAvviso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`GestioneAvviso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idGestioneAvviso` INT NOT NULL,
  `idPersona` INT(11) NOT NULL,
  INDEX `fk_idPersona_idx` (`idPersona` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `DB_orari`.`Persona` (`idPersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `kf_idAvviso`
    FOREIGN KEY (`idGestioneAvviso`)
    REFERENCES `DB_orari`.`Avviso` (`idAvviso`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`GestioneCalendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`GestioneCalendario` (
  `intGestioneCalendario` INT NOT NULL AUTO_INCREMENT,
  `idGestioneCalendario` INT NOT NULL,
  `idPersona` INT NOT NULL,
  INDEX `idPersona_fk_idx` (`idPersona` ASC),
  PRIMARY KEY (`intGestioneCalendario`),
  CONSTRAINT `idPersona_fk`
    FOREIGN KEY (`idPersona`)
    REFERENCES `DB_orari`.`Persona` (`idPersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `idCalendario_fk`
    FOREIGN KEY (`idGestioneCalendario`)
    REFERENCES `DB_orari`.`CalendarioDidattico` (`idCalendarioAccademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_orari`.`GestioneOrario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_orari`.`GestioneOrario` (
  `idGstioneOrario` INT NOT NULL AUTO_INCREMENT,
  `idGestioneOrario` INT NOT NULL,
  `idSegretario` INT NOT NULL,
  INDEX `idOrario_fk_idx` (`idGestioneOrario` ASC),
  INDEX `idSegretario_fk_idx` (`idSegretario` ASC),
  PRIMARY KEY (`idGstioneOrario`),
  CONSTRAINT `idSegretario_fk`
    FOREIGN KEY (`idSegretario`)
    REFERENCES `DB_orari`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOrario_fk`
    FOREIGN KEY (`idGestioneOrario`)
    REFERENCES `DB_orari`.`OrarioDidattico` (`idOrarioDidattico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into Gruppo(idGruppo, descrizione) VALUES (1,'studente');
insert into Gruppo(idGruppo, descrizione) VALUES (2,'professore');
insert into Gruppo(idGruppo, descrizione) VALUES (3,'segretario');
insert into Gruppo(idGruppo, descrizione) VALUES (4,'bibliotecario');
insert into Gruppo(idGruppo, descrizione) VALUES (5,'collaboratoreEsterno');

insert into Persona(idPersona,nome,cognome, telefono, email, idGruppo) VALUES (124535,'ludovico','genoveffo', 3381234354, 'ludovico.genoveffo@gmail.com',1);
insert into Persona(idPersona,nome,cognome, telefono, email, idGruppo) VALUES (120035,'mauro','fibra', 3352378354,'ludovico.genoveffo@gmail.com',2);
insert into Persona(idPersona,nome,cognome, telefono, email, idGruppo) VALUES (124123,'tina','tatangelo', 3381967954,'ludovico.genoveffo@gmail.com', 3);

insert into Avviso(descrizione,idCorso) VALUES ('le lezioni sono sospese', 'E10104');
insert into Avviso(descrizione) VALUES ('domani autogestione');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
